### ISSUE TITLE
Handle gifv

### ISSUE THREAD

**Issue by Pancakeo** [Pancakeo/everlasting_kogmaw#95]
http://i.imgur.com/MM0tT3E.gifv

**Comment by Pancakeo** [comment]
And webm, since it's the same

**Comment by jvinal** [comment]
I am pretty neat

**Comment by Pancakeo** [comment]
Minor issue - clicking Play scrolls to bottom, which isn't desired. Probably just need to use another event for the original scroll, or remove it altogether. (canplaythrough is fired everytime Play is pressed)

**Comment by Pancakeo** [comment]
<video> control should have autoplay and start muted.

**Comment by Pancakeo** [comment]
Added loop/mute/scroll fix
